---
title: "11_3d"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)

trace(grDevices::png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
```



```{r}
dat <- readr::read_csv(here::here("30daymapchallenge/02_line/20211010-140208 - Todtnau.txt"))
dat <- janitor::clean_names(dat)


sfdat <- dat %>% 
  filter(latitude < 47.831) %>% 
  filter(longitude < 7.955) %>% 
  mutate(dt = lubridate::as_datetime(date_time)) %>% 
  filter(dt > lubridate::as_datetime("2021-10-10 14:06:00")) %>% 
  filter(dt < lubridate::as_datetime("2021-10-10 14:29:00")) %>% 
  st_as_sf(coords = c("longitude", "latitude")) 

sfdat %>% 
  ggplot() +
  # geom_sf(aes(col = altitude_m))
  geom_sf()

sfdat_line <- sfdat %>% 
  group_by(group = 1) %>% 
  summarize() %>% 
  st_cast("LINESTRING")

sfdat_line %>% 
  ggplot() +
  # geom_sf(aes(col = altitude_m))
  geom_sf(
    # aes(col = speed_m_s)
    )



```





```{r font}
library(showtext)

font_add_google("Irish Grover", "Irish Grover")

font_families()
```









```{r}
# https://stackoverflow.com/questions/46717440/map-aesthetics-to-linestring-geometries-with-sf-in-r
ldat <- sfdat %>% 
  slice(rep(1:n(), each = 2)) %>%
  slice(-c(1, n())) %>%
  mutate(linegroup = lapply(1:(n()/2), function(x) rep(x, 2)) %>% unlist) %>% 
  ungroup
line <- st_as_sf(ldat, coords = c("long", "lat"), crs = 4326) %>%
  group_by(linegroup) %>%
  summarise(speed = last(speed_m_s), 
            accuracy = last(accuracy_m), 
            altitude = last(altitude_m), 
            do_union = FALSE) %>%
  st_cast("LINESTRING")

# 
# speckle <- function(x, colour, proportion) {
#   raster_dim <- dim(x)
#   n_pixels <- prod(raster_dim)
#   n_speckles <- n_pixels * proportion
#   x[sample(length(x), n_speckles)] <- farver::encode_native(colour)
#   x
# }
# 
# g <- ggplot(line) +
#   ggfx::with_custom(
#   geom_sf(aes(color = speed, 
#               size = altitude
#               ), 
#           show.legend = "line", 
#           lineend = "round"
#           ),
#     filter = speckle,
#     colour = 'forestgreen',
#     proportion = 0.05
#   
#   ) +
#   geom_sf(aes(color = speed, 
#               size = altitude
#               ), 
#           show.legend = "line", 
#           lineend = "round"
#           ) +
# 
#   labs(title = "Hasenhorn\nCoaster" #, 
#        # caption = "Data: GPS Logger\nViz: @aghaynes"
#        ) +
#   scale_color_continuous(name = "Speed (m/s)", low = "#ffffcc", high = "#e31a1c") +
#   scale_size_continuous(name = "Altitude (m)") +
#   theme_void() +
#   theme(
#     plot.background = element_rect(fill = rgb(180,209,19, maxColorValue = 350), colour = NA),
#     plot.title = element_text(hjust = 1, 
#                               family = "Irish Grover", 
#                               size = 20,
#                               margin = margin(t = 0, b = -50)),
#     plot.title.position = "panel",
#     legend.position=c(.85,.55),
#     legend.title = element_text(face = "bold", 
#                                 hjust = 1, 
#                                 family = "Irish Grover"),
#     legend.text = element_text(face = "bold", 
#                                hjust = 1, 
#                                family = "Irish Grover"), 
#     plot.caption.position = "plot",
#     plot.caption = element_text(hjust = 0, vjust = 1)
#     
#   )
# 
# g
# ggsave(here::here("30daymapchallenge/02_line/fig.png"))


# library(cowplot)
# 
# g +
#   draw_image("30daymapchallenge/02_line/Logo.png", scale = .5)

```





```{r}

library(raster)
library(rayshader)
library(elevatr)


location <- line
# location <- st_as_sf(as.data.frame(t(as.data.frame(location$coords))), coords = c("x", "y"), crs = 4326)
buff <- st_buffer(location, .01)
zscale <- 1
raster <- set_bbox_side_length(
  location,
  15000
) |> 
  # get_tiles(resolution = zscale) |> 
  get_elev_raster(14, )
  # merge_rasters() |> 
  # raster()

raster2 <- crop(raster, buff)

surface_matrix <- raster_to_matrix(raster2)
# surface_matrix <- surface_matrix[1:800, 1:800]

# color_pal <- function(n = 255, bias = 1) {
#   pal <- colorRampPalette(
#     c("black", "white"),
#     bias = bias
#   )
#   return(pal(n))
# }
# rayvista? https://github.com/h-a-graham/rayvista
# devtools::install_github("h-a-graham/rayvista", dependencies=TRUE)
# 
# location_centroid <- st_centroid(location)
# 
# vista <- rayvista::plot_3d_vista(req_area = location %>% st_crs(4326),
#                                    # lat = location_centroid$lat, 
#                        # long = location_centroid$long,
#                        radius = 2000, 
#                        overlay_detail = 13,
#                        overlay_alpha = .6,
#                        elevation_detail = 11, 
#                        show_vista = TRUE)




surface_hillshade <- surface_matrix %>% 
  height_shade(
    # texture = colorRampPalette(
    #   c("grey20", "white"), 
    #   bias = 1
    # )(255)
    ) %>% 
  add_shadow(texture_shade(surface_matrix, detail = 0.9, brightness = 15), 0.7) %>% 
  add_shadow(ray_shade(surface_matrix, 
                       sunangle = 180,
                       sunaltitude = 80, 
                       zscale = zscale, 
                       multicore = TRUE), 0) |> 
  add_shadow(ambient_shade(surface_matrix, zscale = zscale)) %>% 
  # add_water(detect_water(surface_matrix, zscale = zscale, min_area = 10, max_height = 500)) %>% 
  add_overlay(generate_line_overlay(heightmap = surface_matrix, 
                                     geometry = location, 
                                     extent = raster::extent(raster2),
                                     color = "red", 
                                     linewidth = .5)) #%>% 
  # add_overlay(generate_polygon_overlay(heightmap = surface_matrix, 
  #                                      geometry = buff %>% dplyr::mutate(fill = "#00000000"), 
  #                                      extent = raster::extent(raster2),
  #                                      linecolor = "pink", data_column_fill = "fill"))





plot_3d(surface_hillshade,
        surface_matrix,
        windowsize = c(800, 800),
        zscale = 2,
        zoom = 0.75,
        solid = FALSE,
        theta = 250,
        phi = 25)

# render_highquality(here::here("30daymapchallenge", "10_raster", "fig.png"))
render_highquality(here::here("30daymapchallenge", 
                              "11_3d", 
                              "rayshader.png"), 
                   # lightintensity = 1000, 
                   parallel = TRUE
                   )

# png(here::here("30daymapchallenge", "10_raster", "fig.png"), width = 10, height = 10, units = "cm", res = 300)
# plot_map(surface_hillshade,
#          surface_matrix, )
# dev.off()




```


