---
title: "Astronauts"
output: html_document
---

Data comes from https://data.mendeley.com/datasets/86tsnnbv2w/1

```{r setup, include=FALSE}
dat <- readr::read_csv("International Astronaut Database.csv")
```

```{r}
library(tidyverse)
remotes::install_github("coolbutuseless/ggblur")
library(ggblur)

names(dat)[5:6] <- c("n_flights", "flighttime")

dat %>%
  mutate(days = str_sub(flighttime, 1,3),
         days = as.numeric(days),
         first_flight = str_extract(Flights, "[:digit:]{4}"),
         first_flight = as.numeric(first_flight),
         first = min(first_flight),
         first_flight = first_flight - first) %>%
  arrange(days) %>%
  ggplot(aes(y = first_flight, x = days, group = Name)) +
  geom_linerange(aes(xmin = 0, xmax = days), col = "white") +
  geom_point_blur(col = "white", blur_size = .5, size = .5) +
  xlim(0, 1000) +
  # coord_flip() +
  coord_polar() +
  theme_dark() +
  ggtitle("Time in Space") +
  theme(plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        axis.text = element_text(colour = "white"),
        axis.text.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```



